pipeline:
  test:
    image: node:11
    commands:
      - npm install
      - npm run coverage
      - npm run linter
    when:
      event:
      - push
      - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: DEV_QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: DEV_QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-translation-service
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch:
        - master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NGINX_IMAGE
      - DEV_NGINX_TAG
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KUBE_NAMESPACE
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_PROTOCOL
      - DEV_WHITELIST
      - DEV_API_REF_URL
      - DEV_API_REF_PROTOCOL
      - DEV_API_COP_URL
      - DEV_API_COP_PROTOCOL
      - DEV_API_FORM_URL
      - DEV_API_FORM_PROTOCOL
      - DEV_ENGINE_URL
      - DEV_ENGINE_PROTOCOL
      - DEV_WWW_URL
      - DEV_WWW_PROTOCOL
      - DEV_REDIS_TOKEN
      - DEV_REDIS_PROTOCOL
      - DEV_REDIS_URL
      - DEV_TRANSLATION_KEYCLOAK_CLIENT_ID
      - DEV_TRANSLATION_PORT
      - DEV_TRANSLATION_KUBE_NAMESPACE
      - DEV_TRANSLATION_IMAGE
      - DEV_TRANSLATION_NAME
      - DEV_TRANSLATION_PRIVATE_KEY_PATH
      - DEV_TRANSLATION_PRIVATE_KEY
      - DEV_TRANSLATION_CORS_ORIGIN
    commands:
      - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
      - export NGINX_TAG=$${DEV_NGINX_TAG}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
      - export WHITELIST=$${DEV_WHITELIST}
      - export API_REF_URL=$${DEV_API_REF_URL}
      - export API_REF_PROTOCOL=$${DEV_API_REF_PROTOCOL}
      - export API_COP_URL=$${DEV_API_COP_URL}
      - export API_COP_PROTOCOL=$${DEV_API_COP_PROTOCOL}
      - export API_FORM_URL=$${DEV_API_FORM_URL}
      - export API_FORM_PROTOCOL=$${DEV_API_FORM_PROTOCOL}
      - export ENGINE_URL=$${DEV_ENGINE_URL}
      - export ENGINE_PROTOCOL=$${DEV_ENGINE_PROTOCOL}
      - export WWW_URL=$${DEV_WWW_URL}
      - export WWW_PROTOCOL=$${DEV_WWW_PROTOCOL}
      - export REDIS_TOKEN=$${DEV_REDIS_TOKEN}
      - export REDIS_PROTOCOL=$${DEV_REDIS_PROTOCOL}
      - export REDIS_URL=$${DEV_REDIS_URL}
      - export TRANSLATION_KEYCLOAK_CLIENT_ID=$${DEV_TRANSLATION_KEYCLOAK_CLIENT_ID}
      - export TRANSLATION_PORT=$${DEV_TRANSLATION_PORT}
      - export TRANSLATION_KUBE_NAMESPACE=$${DEV_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_IMAGE=$${DEV_TRANSLATION_IMAGE}
      - export TRANSLATION_NAME=$${DEV_TRANSLATION_NAME}
      - export TRANSLATION_PRIVATE_KEY_PATH=$${DEV_TRANSLATION_PRIVATE_KEY_PATH}
      - export TRANSLATION_PRIVATE_KEY=$${DEV_TRANSLATION_PRIVATE_KEY}
      - export TRANSLATION_CORS_ORIGIN=$${DEV_TRANSLATION_CORS_ORIGIN}
      - export KUBE_NAMESPACE=$${DEV_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_NGINX_IMAGE
      - STAGING_NGINX_TAG
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_KUBE_NAMESPACE
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_PROTOCOL
      - STAGING_WHITELIST
      - STAGING_API_REF_URL
      - STAGING_API_REF_PROTOCOL
      - STAGING_API_COP_URL
      - STAGING_API_COP_PROTOCOL
      - STAGING_API_FORM_URL
      - STAGING_API_FORM_PROTOCOL
      - STAGING_ENGINE_URL
      - STAGING_ENGINE_PROTOCOL
      - STAGING_WWW_URL
      - STAGING_WWW_PROTOCOL
      - STAGING_REDIS_TOKEN
      - STAGING_REDIS_PROTOCOL
      - STAGING_REDIS_URL
      - STAGING_TRANSLATION_KEYCLOAK_CLIENT_ID
      - STAGING_TRANSLATION_PORT
      - STAGING_TRANSLATION_KUBE_NAMESPACE
      - STAGING_TRANSLATION_IMAGE
      - STAGING_TRANSLATION_NAME
      - STAGING_TRANSLATION_PRIVATE_KEY_PATH
      - STAGING_TRANSLATION_PRIVATE_KEY
      - STAGING_TRANSLATION_CORS_ORIGIN
    commands:
      - export NGINX_IMAGE=$${STAGING_NGINX_IMAGE}
      - export NGINX_TAG=$${STAGING_NGINX_TAG}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${STAGING_KEYCLOAK_PROTOCOL}
      - export WHITELIST=$${STAGING_WHITELIST}
      - export API_REF_URL=$${STAGING_API_REF_URL}
      - export API_REF_PROTOCOL=$${STAGING_API_REF_PROTOCOL}
      - export API_COP_URL=$${STAGING_API_COP_URL}
      - export API_COP_PROTOCOL=$${STAGING_API_COP_PROTOCOL}
      - export API_FORM_URL=$${STAGING_API_FORM_URL}
      - export API_FORM_PROTOCOL=$${STAGING_API_FORM_PROTOCOL}
      - export ENGINE_URL=$${STAGING_ENGINE_URL}
      - export ENGINE_PROTOCOL=$${STAGING_ENGINE_PROTOCOL}
      - export WWW_URL=$${STAGING_WWW_URL}
      - export WWW_PROTOCOL=$${STAGING_WWW_PROTOCOL}
      - export REDIS_TOKEN=$${STAGING_REDIS_TOKEN}
      - export REDIS_PROTOCOL=$${STAGING_REDIS_PROTOCOL}
      - export REDIS_URL=$${STAGING_REDIS_URL}
      - export TRANSLATION_KEYCLOAK_CLIENT_ID=$${STAGING_TRANSLATION_KEYCLOAK_CLIENT_ID}
      - export TRANSLATION_PORT=$${STAGING_TRANSLATION_PORT}
      - export TRANSLATION_KUBE_NAMESPACE=$${STAGING_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_IMAGE=$${STAGING_TRANSLATION_IMAGE}
      - export TRANSLATION_NAME=$${STAGING_TRANSLATION_NAME}
      - export TRANSLATION_PRIVATE_KEY_PATH=$${STAGING_TRANSLATION_PRIVATE_KEY_PATH}
      - export TRANSLATION_PRIVATE_KEY=$${STAGING_TRANSLATION_PRIVATE_KEY}
      - export TRANSLATION_CORS_ORIGIN=$${STAGING_TRANSLATION_CORS_ORIGIN}
      - export KUBE_NAMESPACE=$${STAGING_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_NGINX_IMAGE
      - PRODUCTION_NGINX_TAG
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_KUBE_NAMESPACE
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_PROTOCOL
      - PRODUCTION_WHITELIST
      - PRODUCTION_API_REF_URL
      - PRODUCTION_API_REF_PROTOCOL
      - PRODUCTION_API_COP_URL
      - PRODUCTION_API_COP_PROTOCOL
      - PRODUCTION_API_FORM_URL
      - PRODUCTION_API_FORM_PROTOCOL
      - PRODUCTION_ENGINE_URL
      - PRODUCTION_ENGINE_PROTOCOL
      - PRODUCTION_WWW_URL
      - PRODUCTION_WWW_PROTOCOL
      - PRODUCTION_REDIS_TOKEN
      - PRODUCTION_REDIS_PROTOCOL
      - PRODUCTION_REDIS_URL
      - PRODUCTION_TRANSLATION_KEYCLOAK_CLIENT_ID
      - PRODUCTION_TRANSLATION_PORT
      - PRODUCTION_TRANSLATION_KUBE_NAMESPACE
      - PRODUCTION_TRANSLATION_IMAGE
      - PRODUCTION_TRANSLATION_NAME
      - PRODUCTION_TRANSLATION_PRIVATE_KEY_PATH
      - PRODUCTION_TRANSLATION_PRIVATE_KEY
      - PRODUCTION_TRANSLATION_CORS_ORIGIN
    commands:
      - export NGINX_IMAGE=$${PRODUCTION_NGINX_IMAGE}
      - export NGINX_TAG=$${PRODUCTION_NGINX_TAG}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${PRODUCTION_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${PRODUCTION_KEYCLOAK_PROTOCOL}
      - export WHITELIST=$${PRODUCTION_WHITELIST}
      - export API_REF_URL=$${PRODUCTION_API_REF_URL}
      - export API_REF_PROTOCOL=$${PRODUCTION_API_REF_PROTOCOL}
      - export API_COP_URL=$${PRODUCTION_API_COP_URL}
      - export API_COP_PROTOCOL=$${PRODUCTION_API_COP_PROTOCOL}
      - export API_FORM_URL=$${PRODUCTION_API_FORM_URL}
      - export API_FORM_PROTOCOL=$${PRODUCTION_API_FORM_PROTOCOL}
      - export ENGINE_URL=$${PRODUCTION_ENGINE_URL}
      - export ENGINE_PROTOCOL=$${PRODUCTION_ENGINE_PROTOCOL}
      - export WWW_URL=$${PRODUCTION_WWW_URL}
      - export WWW_PROTOCOL=$${PRODUCTION_WWW_PROTOCOL}
      - export REDIS_TOKEN=$${PRODUCTION_REDIS_TOKEN}
      - export REDIS_PROTOCOL=$${PRODUCTION_REDIS_PROTOCOL}
      - export REDIS_URL=$${PRODUCTION_REDIS_URL}
      - export TRANSLATION_KEYCLOAK_CLIENT_ID=$${PRODUCTION_TRANSLATION_KEYCLOAK_CLIENT_ID}
      - export TRANSLATION_PORT=$${PRODUCTION_TRANSLATION_PORT}
      - export TRANSLATION_KUBE_NAMESPACE=$${PRODUCTION_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_IMAGE=$${PRODUCTION_TRANSLATION_IMAGE}
      - export TRANSLATION_NAME=$${PRODUCTION_TRANSLATION_NAME}
      - export TRANSLATION_PRIVATE_KEY_PATH=$${PRODUCTION_TRANSLATION_PRIVATE_KEY_PATH}
      - export TRANSLATION_PRIVATE_KEY=$${PRODUCTION_TRANSLATION_PRIVATE_KEY}
      - export TRANSLATION_CORS_ORIGIN=$${PRODUCTION_TRANSLATION_CORS_ORIGIN}
      - export KUBE_NAMESPACE=$${PRODUCTION_TRANSLATION_KUBE_NAMESPACE}
      - export TRANSLATION_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment
