pipeline:
  test:
    image: node:11
    commands:
      - npm install
      - npm run coverage
      - npm run linter
    when:
      event:
      - push
      - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-translation-service
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch:
        - master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_SECRET
      - DEV_PRIVATE_FORM_NAME
      - DEV_PRIVATE_WORKFLOW_ENGINE_NAME
      - DEV_PRIVATE_UI_NAME
      - DEV_PRIVATE_POSTGREST_NAME
      - DEV_PRIVATE_REFDATA_URL
      - DEV_EXT_DOMAIN
      - DEV_PROTOCOL
      - DEV_SESSION_NAME
      - DEV_SESSION_SECRET
      - DEV_PRIVATE_POSTGREST_NAME
      - DEV_WHITELIST
      - DEV_CORS_ORIGIN
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEV_KEYCLOAK_SECRET}
      - export EXT_DOMAIN=$${DEV_EXT_DOMAIN}
      - export PROTOCOL=$${DEV_PROTOCOL}
      - export PRIVATE_FORM_NAME=$${DEV_PRIVATE_FORM_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${DEV_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_UI_NAME=$${DEV_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${DEV_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_REFDATA_URL=$${DEV_PRIVATE_REFDATA_URL}
      - export SESSION_NAME=$${DEV_SESSION_NAME}
      - export SESSION_SECRET=$${DEV_SESSION_SECRET}
      - export PRIVATE_POSTGREST_NAME=$${DEV_PRIVATE_POSTGREST_NAME}
      - export WHITELIST=$${DEV_WHITELIST}
      - export CORS_ORIGIN=$${DEV_CORS_ORIGIN}
      - export IMAGE_TAG=${DRONE_BUILD_NUMBER}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_NAME
      - STAGING_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_SECRET
      - STAGING_PRIVATE_FORM_NAME
      - STAGING_PRIVATE_WORKFLOW_ENGINE_NAME
      - STAGING_PRIVATE_UI_NAME
      - STAGING_PRIVATE_POSTGREST_NAME
      - STAGING_PRIVATE_REFDATA_URL
      - STAGING_EXT_DOMAIN
      - STAGING_PROTOCOL
      - STAGING_SESSION_NAME
      - STAGING_SESSION_SECRET
      - STAGING_PRIVATE_POSTGREST_NAME
      - STAGING_WHITELIST
      - STAGING_CORS_ORIGIN
    commands:
      - export NAME=$${STAGING_NAME}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${STAGING_KEYCLOAK_SECRET}
      - export EXT_DOMAIN=$${STAGING_EXT_DOMAIN}
      - export PROTOCOL=$${STAGING_PROTOCOL}
      - export PRIVATE_FORM_NAME=$${STAGING_PRIVATE_FORM_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${STAGING_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_UI_NAME=$${STAGING_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${STAGING_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_REFDATA_URL=$${STAGING_PRIVATE_REFDATA_URL}
      - export SESSION_NAME=$${STAGING_SESSION_NAME}
      - export SESSION_SECRET=$${STAGING_SESSION_SECRET}
      - export PRIVATE_POSTGREST_NAME=$${STAGING_PRIVATE_POSTGREST_NAME}
      - export WHITELIST=$${STAGING_WHITELIST}
      - export CORS_ORIGIN=$${STAGING_CORS_ORIGIN}
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_NAME
      - PRODUCTION_KUBE_NAMESPACE
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_SECRET
      - PRODUCTION_PRIVATE_FORM_NAME
      - PRODUCTION_PRIVATE_WORKFLOW_ENGINE_NAME
      - PRODUCTION_PRIVATE_UI_NAME
      - PRODUCTION_PRIVATE_POSTGREST_NAME
      - PRODUCTION_PRIVATE_REFDATA_URL
      - PRODUCTION_EXT_DOMAIN
      - PRODUCTION_PROTOCOL
      - PRODUCTION_SESSION_NAME
      - PRODUCTION_SESSION_SECRET
      - PRODUCTION_PRIVATE_POSTGREST_NAME
      - PRODUCTION_WHITELIST
      - PRODUCTION_CORS_ORIGIN
    commands:
      - export NAME=$${PRODUCTION_NAME}
      - export KUBE_NAMESPACE=$${PRODUCTION_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${PRODUCTION_KEYCLOAK_SECRET}
      - export EXT_DOMAIN=$${PRODUCTION_EXT_DOMAIN}
      - export PROTOCOL=$${PRODUCTION_PROTOCOL}
      - export PRIVATE_FORM_NAME=$${PRODUCTION_PRIVATE_FORM_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${PRODUCTION_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_UI_NAME=$${PRODUCTION_PRIVATE_UI_NAME}
      - export PRIVATE_POSTGREST_NAME=$${PRODUCTION_PRIVATE_POSTGREST_NAME}
      - export PRIVATE_REFDATA_URL=$${PRODUCTION_PRIVATE_REFDATA_URL}
      - export SESSION_NAME=$${PRODUCTION_SESSION_NAME}
      - export SESSION_SECRET=$${PRODUCTION_SESSION_SECRET}
      - export PRIVATE_POSTGREST_NAME=$${PRODUCTION_PRIVATE_POSTGREST_NAME}
      - export WHITELIST=$${PRODUCTION_WHITELIST}
      - export CORS_ORIGIN=$${PRODUCTION_CORS_ORIGIN}
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment
