---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.TRANSLATION_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.TRANSLATION_NAME}}"
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.TRANSLATION_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        env:
        - name: PROXY_SERVICE_HOST
          value: "127.0.0.1"
        - name: PROXY_SERVICE_PORT
          value: "{{.TRANSLATION_PORT}}"
        - name: SERVER_CERT
          value: "/certs/tls.crt"
        - name: SERVER_KEY
          value: "/certs/tls.key"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: LOG_FORMAT_NAME
          value: 'json'
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: STATSD_METRICS
          value: "FALSE"
        ports:
        - name: https
          containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.TRANSLATION_NAME}}"
        image: "{{.TRANSLATION_IMAGE}}:{{.TRANSLATION_TAG}}"
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /api/translation/readiness
            port: {{.TRANSLATION_PORT}}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /api/translation/healthz
            port: {{.TRANSLATION_PORT}}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
          - name: enccerts
            mountPath: /enccerts
        env:
        - name: TRANSLATION_KEYCLOAK_CLIENT_ID
          value: "{{.TRANSLATION_KEYCLOAK_CLIENT_ID}}"
        - name: KEYCLOAK_URI
          value: "{{.KEYCLOAK_PROTOCOL}}{{.KEYCLOAK_URL}}"
        - name: KEYCLOAK_REALM
          value: "{{.KEYCLOAK_REALM}}"
        - name: API_FORM_URI
          value: "{{.API_FORM_PROTOCOL}}{{.API_FORM_URL}}"
        - name: API_COP_URI
          value: "{{.API_COP_PROTOCOL}}{{.API_COP_URL}}"
        - name: API_REF_URI
          value: "{{.API_REF_PROTOCOL}}{{.API_REF_URL}}"
        - name: ENGINE_URI
          value: "{{.ENGINE_PROTOCOL}}{{.ENGINE_URL}}"
        - name: WWW_URI
          value: "{{.WWW_PROTOCOL}}{{.WWW_URL}}"
        - name: TRANSLATION_CORS_ORIGIN
          value: "{{.TRANSLATION_CORS_ORIGIN}}"
        - name: TRANSLATION_PORT
          value: "{{.TRANSLATION_PORT}}"
        - name: TRANSLATION_PRIVATE_KEY_PATH
          value: "{{.TRANSLATION_PRIVATE_KEY_PATH}}"
        - name: TRANSLATION_LOG_LEVEL
          value: "{{.TRANSLATION_LOG_LEVEL}}"
        - name: REDIS_SSL
          value: "{{.REDIS_SSL}}"
        - name: REDIS_URI
          value: "{{.REDIS_URL}}"
        - name: REDIS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{.TRANSLATION_NAME}}
              key: redisAuthToken
      volumes:
      - name: enccerts
        secret:
          secretName: {{.TRANSLATION_NAME}}
          items:
          - key: enc-key.pem
            path: enc-key.pem
            mode: 256
      - name: certs
        secret:
          secretName: "{{.TRANSLATION_NAME}}-pod-tls"
