---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.NAME}}
spec:
  selector:
    matchLabels:
      name: {{.NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        env:
        - name: PROXY_SERVICE_HOST
          value: "127.0.0.1"
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: ENABLE_UUID_PARAM
          value: {{.ENABLE_UUID}}
        - name: LOG_FORMAT_NAME
          value: 'json'
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: STATSD_METRICS
          value: "FALSE"
        ports:
        - name: https
          containerPort: 10443
      - name: {{.NAME}}
        image: quay.io/ukhomeofficedigital/cop-private-translation-service:{{.IMAGE_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /api/translation/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /api/translation/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
          - name: enccerts
            mountPath: /enccerts
        env:
        - name: AUTH_CLIENT_ID
          value: {{.NAME}}
        - name: AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: authClientSecret
        - name: AUTH_URL
          value: {{.KEYCLOAK_URL}}
        - name: AUTH_REALM
          value: {{.KEYCLOAK_REALM}}
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: sessionSecret
        - name: SESSION_NAME
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: sessionName
        - name: PROTOCOL
          value: {{.PROTOCOL}}
        - name: PRIVATE_REFDATA_URL
          value: {{.PRIVATE_REFDATA_URL}}
        - name: PRIVATE_FORM_NAME
          value: {{.PRIVATE_FORM_NAME}}
        - name: PRIVATE_OPERATIONAL_DATA_URL
          value: {{.PRIVATE_OPERATIONAL_DATA_URL}}
        - name: PRIVATE_WORKFLOW_ENGINE_NAME
          value: {{.PRIVATE_WORKFLOW_ENGINE_NAME}}
        - name: PRIVATE_UI_NAME
          value: {{.PRIVATE_UI_NAME}}
        - name: EXT_DOMAIN
          value: {{.EXT_DOMAIN}}
        - name: CORS_ORIGIN
          value: {{.CORS_ORIGIN}}
      volumes:
      - name: enccerts
        secret:
          secretName: mobileid
          items:
          - key: mobileid-key.pem
            path: mobileid-key.pem
            mode: 256
