---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.NAME}}
spec:
  selector:
    matchLabels:
      name: {{.NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/borders-cfssl-sidekick:bd4901b5a28c
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --domain={{.NAME}}.{{.KUBE_NAMESPACE}}.svc.cluster.local
          - --url={{.INTERNAL_CA_URL}}
          - --verbose=True
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: "100m"
         requests:
          memory: "50Mi"
          cpu: "100m"
        env:
        - name: PROXY_SERVICE_HOST
          value: "127.0.0.1"
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: SERVER_CERT
          value: "/certs/tls.pem"
        - name: SERVER_KEY
          value: "/certs/tls-key.pem"
        - name: SSL_CIPHERS
          value: "ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH:!aNULL"
        - name: ENABLE_UUID_PARAM
          value: "HEADER"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: PORT_IN_HOST_HEADER
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        - name: ADD_NGINX_SERVER_CFG
          value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        - name: ADD_NGINX_LOCATION_CFG
          value: |
            gzip off;
            proxy_buffer_size         128k;
            proxy_buffers             4 256k;
            proxy_busy_buffers_size   256k;
            add_header       X-Frame-Options 'ALLOW-FROM {{.PROTOCOL}}{{.PRIVATE_UI_NAME}}.{{.EXT_DOMAIN}}' always;
        - name: LOG_FORMAT_NAME
          value: "json"
        - name: NO_LOGGING_URL_PARAMS
          value: "{{.NO_LOGGING_URL_PARAMS}}"
        - name: NO_LOGGING_BODY
          value: "{{.NO_LOGGING_BODY}}"
        - name: NO_LOGGING_RESPONSE
          value: "{{.NO_LOGGING_RESPONSE}}"
        - name: STATSD_METRICS
          value: "FALSE"
        ports:
        - name: https
          containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: {{.NAME}}
        image: quay.io/ukhomeofficedigital/cop-private-translation-service:{{.IMAGE_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /api/translation/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /api/translation/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: enccerts
            mountPath: /enccerts
        env:
        - name: AUTH_CLIENT_ID
          value: {{.NAME}}
        - name: AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: authClientSecret
        - name: AUTH_URL
          value: {{.KEYCLOAK_URL}}
        - name: AUTH_REALM
          value: {{.KEYCLOAK_REALM}}
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: sessionSecret
        - name: SESSION_NAME
          valueFrom:
            secretKeyRef:
              name: {{.NAME}}
              key: sessionName
        - name: PROTOCOL
          value: {{.PROTOCOL}}
        - name: INT_DOMAIN
          value: {{.INT_DOMAIN}}
        - name: PRIVATE_FORM_NAME
          value: {{.PRIVATE_FORM_NAME}}
        - name: PRIVATE_POSTGREST_NAME
          value: {{.PRIVATE_POSTGREST_NAME}}
        - name: PRIVATE_WORKFLOW_ENGINE_NAME
          value: {{.PRIVATE_WORKFLOW_ENGINE_NAME}}
      volumes:
      - name: bundle
        configMap:
          name: bundle
      - name: certs
        emptyDir: {}
      - name: enccerts
        secret:
          secretName: mobileid
          items:
          - key: mobileid-key.pem
            path: mobileid-key.pem
            mode: 256
