---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{.TRANSLATION_NAME}}
spec:
  egress:
    - {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-external
      ports:
        - port: 10443
          protocol: TCP
  podSelector:
    matchLabels:
      name: {{.TRANSLATION_NAME}}
  policyTypes:
    - Ingress
    - Egress
