export const ERROR_STATUS = {
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
};

